### ISSUE TITLE
Bug in Wikidata Import and/or Export: Qnode Q2046-S1

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#124]
KgtkReader: File_path.suffix: .tsv
KgtkReader: reading file data/wikidata-20181210-all-qualifiers-pre-20101201-sorted.tsv
header: id      node1   label   node2   node2;wikidatatype      val_type        entity_type     datahash        precision       calendar
node1 column found, this is a KGTK edge file
KgtkReader: Special columns: node1=1 label=2 node2=3 id=0
KgtkReader: Reading an edge file.
Traceback (most recent call last):
  File "/home/rogers/elicit/github/kgtk3/kgtk/cli/export_wikidata.py", line 122, in run
    ew.process()
  File "/home/rogers/elicit/github/kgtk3/kgtk/exports/exportwikidata.py", line 739, in process
    result: typing.Mapping[str, typing.Any] = self.process_qnode(qnode_info,
  File "/home/rogers/elicit/github/kgtk3/kgtk/exports/exportwikidata.py", line 583, in process_qnode
    self.process_qnode_edges(result, qnode, edges, qualifier_dict)
  File "/home/rogers/elicit/github/kgtk3/kgtk/exports/exportwikidata.py", line 566, in process_qnode_edges
    self.process_qnode_edge(result, qnode, edge_label, edge_id, edge_row, qualifier_rows)
  File "/home/rogers/elicit/github/kgtk3/kgtk/exports/exportwikidata.py", line 523, in process_qnode_edge
    mainsnak["datavalue"] = self.process_edge_datavalue(value, edge_row, datatype)
  File "/home/rogers/elicit/github/kgtk3/kgtk/exports/exportwikidata.py", line 241, in process_edge_datavalue
    valuemap["numeric-id"] = int(value[1:])
ValueError: invalid literal for int() with base 10: '2046-S1'

Presumably, this was Qnode Q2046-S1.  What is the actual entry in the Wikidata we imported?

**Comment by CraigMiloRogers** [comment]
Fixed, I think.
