### ISSUE TITLE
sort of gz file doesn't work

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#146]
The command with `gz` file doesn't work, exact same command with uncompressed file does work

If `kgtk --help` printed version number, I would report it here.

```
(kgtk) D22ML-PSZEKELY:wikidata-20200803-P31-P279-star pedroszekely$ kgtk sort -i wikidata-20200803-all-edges-P31-P279-star.tsv.gz | gzip > wikidata-20200803-all-edges-P31-P279-star.sorted.tsv.gz
Exception in thread background thread for pid 6520:
Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/sh-1.13.1-py3.7.egg/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/sh-1.13.1-py3.7.egg/sh.py", line 2606, in background_thread
    handle_exit_code(exit_code)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/sh-1.13.1-py3.7.egg/sh.py", line 2304, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/sh-1.13.1-py3.7.egg/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/zcat wikidata-20200803-all-edges-P31-P279-star.tsv.gz

  STDOUT:


  STDERR:
zcat: can't stat: wikidata-20200803-all-edges-P31-P279-star.tsv.gz (wikidata-20200803-all-edges-P31-P279-star.tsv.gz.Z): No such file or directory


INTERNAL ERROR: sh.

Original exception:
===================

    Traceback (most recent call last):
      File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/sh-1.13.1-py3.7.egg/sh.py", line 2082, in __init__
        preexec_fn()
      File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk-0.4.0-py3.7.egg/kgtk/cli/sort.py", line 152, in wait_for_key_spec
        raise KGTKException('INTERNAL ERROR: failed to communicate sort key')
    kgtk.exceptions.KGTKException: INTERNAL ERROR: failed to communicate sort key
```

**Comment by CraigMiloRogers** [comment]
Ah, that's the original `kgtk sort`. Please try `kgtk sort2`.

**Comment by CraigMiloRogers** [comment]
`kgtk sort2` now accepts `.gx` on input and output files.
