### ISSUE TITLE
kgtk query unit tests fail

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#154]
======================================================================
ERROR: test_kgtk_query__named_multi_graph_join (test_kgtk_query.TestKGTKQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/elicit/github/kgtk/kgtk/tests/test_kgtk_query.py", line 267, in test_kgtk_query__named_multi_graph_join
    df = pd.read_csv(f'{self.temp_dir}/out.tsv', sep='\t')
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /tmp/tmpn7l6yj9i/out.tsv does not exist: '/tmp/tmpn7l6yj9i/out.tsv'

**Comment by CraigMiloRogers** [comment]
======================================================================
ERROR: test_kgtk_query_biggest_salary (test_kgtk_query.TestKGTKQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/elicit/github/kgtk/kgtk/tests/test_kgtk_query.py", line 384, in test_kgtk_query_biggest_salary
    df = pd.read_csv(f'{self.temp_dir}/out.tsv', sep='\t')
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /tmp/tmpxm3lwxmi/out.tsv does not exist: '/tmp/tmpxm3lwxmi/out.tsv'

======================================================================
ERROR: test_kgtk_query_count (test_kgtk_query.TestKGTKQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/elicit/github/kgtk/kgtk/tests/test_kgtk_query.py", line 362, in test_kgtk_query_count
    df = pd.read_csv(f'{self.temp_dir}/out.tsv', sep='\t')
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /tmp/tmpgvngdrw5/out.tsv does not exist: '/tmp/tmpgvngdrw5/out.tsv'

======================================================================
ERROR: test_kgtk_query_count_distinct (test_kgtk_query.TestKGTKQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/elicit/github/kgtk/kgtk/tests/test_kgtk_query.py", line 374, in test_kgtk_query_count_distinct
    df = pd.read_csv(f'{self.temp_dir}/out.tsv', sep='\t')
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /tmp/tmpsqmsvgez/out.tsv does not exist: '/tmp/tmpsqmsvgez/out.tsv'

======================================================================
ERROR: test_kgtk_query_date_filter (test_kgtk_query.TestKGTKQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/elicit/github/kgtk/kgtk/tests/test_kgtk_query.py", line 394, in test_kgtk_query_date_filter
    df = pd.read_csv(f'{self.temp_dir}/out.tsv', sep='\t')
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rogers/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /tmp/tmpmyh4ng7e/out.tsv does not exist: '/tmp/tmpmyh4ng7e/out.tsv'

...

**Comment by saggu** [comment]
@CraigMiloRogers it looks like the `kgtk query` command is failing altogether, do you have the latest from `dev` branch and have installed all the requirements from `requirements.txt` ?

**Comment by CraigMiloRogers** [comment]
Adding the new required modules (parsley and odictliteral) solved the problems.  Thanks, I should have thought of this.
