### ISSUE TITLE
`kgtk query` Silently Fails if sqlite3 Is Not Found

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#162]
155% kgtk query -i xxx.tsv -i yyy.tsv

156% kgtk --debug query -i xxx.tsv -i yyy.tsv
[2020-10-15 11:22:23 sqlstore]: IMPORT graph via csv.reader into table graph_21 from /data1/rogers/elicit/github/kgtk/xxx.tsv ...
Traceback (most recent call last):
  File "/home/rogers/elicit/github/kgtk/kgtk/kypher/sqlstore.py", line 554, in add_graph
    self.import_graph_data_via_import(table, file)
  File "/home/rogers/elicit/github/kgtk/kgtk/kypher/sqlstore.py", line 606, in import_graph_data_via_import
    sqlite3 = sh.Command(self.get_sqlite_cmd())
  File "/home/rogers/.local/lib/python3.8/site-packages/sh.py", line 1319, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: sqlite3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rogers/elicit/github/kgtk/kgtk/cli/query.py", line 139, in run
    query = kyquery.KgtkQuery(inputs, store, loglevel=loglevel,
  File "/home/rogers/elicit/github/kgtk/kgtk/kypher/query.py", line 180, in __init__
    store.add_graph(file)
  File "/home/rogers/elicit/github/kgtk/kgtk/kypher/sqlstore.py", line 557, in add_graph
    self.import_graph_data_via_csv(table, file)
  File "/home/rogers/elicit/github/kgtk/kgtk/kypher/sqlstore.py", line 587, in import_graph_data_via_csv
    header = next(csvreader)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rogers/elicit/github/kgtk/kgtk/exceptions.py", line 42, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/home/rogers/elicit/github/kgtk/kgtk/cli/query.py", line 180, in run
    raise KGTKException(str(e) + '\n')
kgtk.exceptions.KGTKException:

**Comment by chalypso** [comment]
It is saying sh.CommandNotFound: sqlite3 which is what it is supposed to do, which is not silent in my book.  It looks like you need to install sqlite3 which is standardly installed in conda environments but maybe you are not using conda.  The testing for the availability and appropriate version of sqlite3 across platforms is not finished yet.

**Comment by CraigMiloRogers** [comment]
When `--debug` wasn't present, the failure was totally silent.  When I added `--debug` I received more useful feedback.

**Comment by szeke** [comment]
Pinging @chalypso

**Comment by chalypso** [comment]
I haven't forgotten about this, but this interacts with Yixiang's recent --check-deps extension proposal.  There are a couple of errors like this one and also using a wrong (too-old) version of sqlite (Amandeep has run into that a few times) that need to be handled in a way that tells people what the issue is, how to check for the dependency and then how to resolve that.  So stay tuned and don't give up on me :-)
