### ISSUE TITLE
Errors in import-wikidata command old dumps

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#173]
**Describe the bug**
Using the latest code in the `dev` branch, I tried to import some json dumps of Wikidata:
```
kgtk import-wikidata -i dumps/20141020.json.gz --node test_import/nodefile.tsv --edge test_import/edgefile.tsv --qual test_import/qual.tsv
```
I tried from a few months/years. All the ones ending in `json.gz` seem to fail. Example of one of the errors with the file above:

```
Exiting worker process 1 (pid 11).
Process Process-2:
Exiting worker process 0 (pid 10).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Process Process-1:
  File "/opt/conda/lib/python3.7/site-packages/pyrallel.lib-0.0.8-py3.7.egg/pyrallel/parallel_processor.py", line 337, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kgtk-0.4.0-py3.7.egg/kgtk/cli/import_wikidata.py", line 1108, in process
    raise KGTKException("Qnode %s is missing its claims" % qnode)
kgtk.exceptions.KGTKException: Qnode P22 is missing its claims
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyrallel.lib-0.0.8-py3.7.egg/pyrallel/parallel_processor.py", line 337, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kgtk-0.4.0-py3.7.egg/kgtk/cli/import_wikidata.py", line 1108, in process
    raise KGTKException("Qnode %s is missing its claims" % qnode)
kgtk.exceptions.KGTKException: Qnode P16 is missing its claims
```

Another error that is the most frequent (makes the workers exit). These happened in most of the dumps I tried:
```
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyrallel.lib-0.0.8-py3.7.egg/pyrallel/parallel_processor.py", line 337, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kgtk-0.4.0-py3.7.egg/kgtk/cli/import_wikidata.py", line 1152, in process
    typ = cp['mainsnak']['datatype']
KeyError: 'datatype'
```
I updated the Google drive with 2 examples producing these errors. @CraigMiloRogers let me know if you need more.

**Comment by dgarijo** [comment]
Today I have experienced this error also in a dump from 2017:

```
Exiting worker process 1 (pid 637).
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyrallel.lib-0.0.8-py3.7.egg/pyrallel/parallel_processor.py", line 337, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kgtk-0.4.0-py3.7.egg/kgtk/cli/import_wikidata.py", line 1152, in process
    typ = cp['mainsnak']['datatype']
KeyError: 'datatype'
```

**Comment by dgarijo** [comment]
I am getting a similar error for most 2018 available dumps:

```
 File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/multiprocess-0.70.10-py3.7.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyrallel.lib-0.0.8-py3.7.egg/pyrallel/parallel_processor.py", line 337, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kgtk-0.4.0-py3.7.egg/kgtk/cli/import_wikidata.py", line 1294, in process
    typ = qcp['datatype']
KeyError: 'datatype'
```

**Comment by dgarijo** [comment]
I am confirming now that I haven't been able to run on any dump from 2016. The error is similar to the one above.

**Comment by CraigMiloRogers** [comment]
This is also issue #108

**Comment by CraigMiloRogers** [comment]
For sample data look on the KGTK Google Drive in `datasets/wikidata_delta`.

**Comment by CraigMiloRogers** [comment]
`kgtk import-wikidata` has been changed to skip the records causing th eproblem.

**Comment by dgarijo** [comment]
The import still fails from dumps between 20141020 and 20150727
Samples may be downloaded from the following links:
- [20141020 ](https://archive.org/download/wikidata-json-20141020/20141020.json.gz)
- [20150727](https://archive.org/download/wikidata-json-20150727/wikidata-20150727-all.json.gz)

**Comment by CraigMiloRogers** [comment]
I've modified the code to persevere when additional fields ar emissing in the JSON file. Use `kgtk import-wikidata --fail-if-missing-data False`, as in
```kgtk --debug --progress \
        import-wikidata \
        -i wikidata-20150727-all.json.gz \
        --single-mapper-queue True \
        --collect-results True \
        --collect-seperately True \
        --use-shm True \
        --edge 20150727.edge.tsv.gz \
        --qual 20150727.qual.tsv.gz \
        --use-mgzip-for-input True \
        --use-mgzip-for-output True \
        --fail-if-missing False
```

**Comment by CraigMiloRogers** [comment]
The changes have been merged into `dev`.

**Comment by dgarijo** [comment]
Thanks, I will test it out

**Comment by dgarijo** [comment]
I get the following error:
```
Importing file...
usage: kgtk [options] command [ / command]*
kgtk: error: unrecognized arguments: --fail-if-missing-data False
```
Maybe you didn't commit the changes, @CraigMiloRogers ?

**Comment by CraigMiloRogers** [comment]
`--fail-if-missing False`, not `--fail-if-missing-data`

**Comment by dgarijo** [comment]
Checked, it's printing out thousands of messages but it seems to be working. Closing issue
