### ISSUE TITLE
KGTK EdgeReader fails for text-embedding 

### ISSUE THREAD

**Issue by filievski** [usc-isi-i2/kgtk#178]
**Describe the bug**
The following command fails with the file `sorted.tsv` which has a version of the first 1000 edges in CSKG with their labels 'lowered' and then sorted.

The error I am getting happens at file reading time, and seems to be connected to the KGTK reader classes: 

```
Traceback (most recent call last):
  File "/Users/filipilievski/mcs/kgtk/kgtk/cli/text_embedding.py", line 214, in main
    property_labels_dict = load_property_labels_file(property_labels_files, error_file, reader_options, value_options, verbose)
  File "/Users/filipilievski/mcs/kgtk/kgtk/cli/text_embedding.py", line 65, in load_property_labels_file
    node_id: str = row[kr.node_column_idx]
AttributeError: 'EdgeReader' object has no attribute 'node_column_idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/filipilievski/mcs/kgtk/kgtk/exceptions.py", line 42, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/filipilievski/mcs/kgtk/kgtk/cli/text_embedding.py", line 369, in run
    main(**kwargs)
  File "/Users/filipilievski/mcs/kgtk/kgtk/cli/text_embedding.py", line 251, in main
    raise KGTKException(str(e))
kgtk.exceptions.KGTKException: 'EdgeReader' object has no attribute 'node_column_idx'
'EdgeReader' object has no attribute 'node_column_idx'
```

**To Reproduce**
```
!kgtk text_embedding \
    --debug --embedding-projector-metadata-path none \
    --embedding-projector-metadata-path none \
    --label-properties "label" \
    --isa-properties "/r/IsA" \
    --description-properties "/r/DefinedAs" \
    --property-value "/r/Causes" "/r/UsedFor" "/r/PartOf" \
    --has-properties "" \
    -f kgtk_format \
    --output-data-format kgtk_format \
    --model bert-large-nli-cls-token \
    --save-embedding-sentence \
    -i sorted.tsv \
    -p sorted.tsv \
    > cskg_embedings.txt
```

**Expected behavior**
I expected to see file which for each node contains its embedding and its generated sentences. As there is an error, no file was generated. Prior to adding the `-p` flag, I was getting a sentence but many labels were missing.

**Desktop (please complete the following information):**
 - OS Catalina 10.15

**Comment by CraigMiloRogers** [comment]
There was a missing line of code! And a typo just after that.

**Comment by CraigMiloRogers** [comment]
And another typo!  And an unwarranted assumption!

**Comment by CraigMiloRogers** [comment]
[cskg_embedings.txt](https://github.com/usc-isi-i2/kgtk/files/5442707/cskg_embedings.txt)

**Comment by CraigMiloRogers** [comment]
Fixed, I think.
