### ISSUE TITLE
Fix Bug in Regex Filter

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#201]
Regex filters are throwing exceptions.  The exceptions indicate short lines. The problems may be in the input file itself, in which case some other component may be at fault.
```
Traceback (most recent call last):tasets/wikidata-20200803/data/all.tsv.gz: 61.9GiB 3:41:37 [0.00 B/s] [=========================================>] 100% ETA 0:00:00
  File "/home/rogers/elicit/github/kgtk2/kgtk/cli/filter.py", line 962, in run
    return process_regex()
  File "/home/rogers/elicit/github/kgtk2/kgtk/cli/filter.py", line 951, in process_regex
    multiple_general_regex(kr, kws, rw, subj_idx, subj_regexes, pred_idx, pred_regexes, obj_idx, obj_regexes)
  File "/home/rogers/elicit/github/kgtk2/kgtk/cli/filter.py", line 808, in multiple_general_regex
    pred_match: typing.Optional[typing.Match] = pred_filter.match(row[pred_idx])
IndexError: list index out of range
```

**Comment by CraigMiloRogers** [comment]
The input file to the filter was corrupted by a bug in `kgtk cat --verbose`.
