### ISSUE TITLE
`kgkt sort2 --gzip-command pigz` did not decompress the input file on centos

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#268]
Reported by @saggu 

!{kgtk_command} {kgtk_options} sort2 --verbose={verbose} --gzip-command={gzip_command} \
 --input-file {temp_folder_path}/claims-and-qualifiers.sorted-by-id.{kgtk_extension} \
 --output-file {temp_folder_path}/claims-and-qualifiers.sorted-by-node1.{kgtk_extension}\
 --columns     node1 \
 --extra       "{sort_extras}"

header pipe: read_fd=4 write_fd=5
sort options pipe: read_fd=6 write_fd=7
gzip output file: /data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/temp/claims-and-qualifiers.sorted-by-node1.tsv.gz
sort command:  { IFS= read -r header ;  { printf "%s\n" "$header" >&5 ; } ;  printf "%s\n" "$header" ;  IFS= read -u 6 -r options ;  LC_ALL=C sort -t '	' $options ; }  | pigz - > '/data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/temp/claims-and-qualifiers.sorted-by-node1.tsv.gz'
gunzip input file: /data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/temp/claims-and-qualifiers.sorted-by-id.tsv.gz
pigz: skipping: /data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/temp/claims-and-qualifiers.sorted-by-id.tsv.gz ends with .gz
Monitoring the cat command (pid=66240).Done reading the input file
Running the sort script (pid=66244).
Reading the KGTK input file header line with KgtkReader
KgtkReader: reading file descriptor 4
header: 
In input header '': Column 0 has an invalid name in the file header
Traceback (most recent call last):
  File "/data/amandeep/Github/kgtk/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/data/amandeep/Github/kgtk/kgtk/cli/sort2.py", line 448, in run
    very_verbose=very_verbose,
  File "/data/amandeep/Github/kgtk/kgtk/io/kgtkreader.py", line 554, in open
    error_file=error_file)
  File "/data/amandeep/Github/kgtk/kgtk/io/kgtkbase.py", line 147, in build_column_name_map
    header_line=header_line, who=who, error_action=error_action, error_file=error_file)
  File "/data/amandeep/Github/kgtk/kgtk/io/kgtkbase.py", line 35, in _yelp
    sys.exit(1)
SystemExit: 1
/data/amandeep/Github/kgtk/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'SystemExit'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException foundTiming: elapsed=0:00:01.361447 CPU=0:00:01.173706 ( 86.2%): sort2 --verbose=True --gzip-command=pigz --input-file /data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/temp/claims-and-qualifiers.sorted-by-id.tsv.gz --output-file /data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/temp/claims-and-qualifiers.sorted-by-node1.tsv.gz --columns node1 --extra --parallel 24 --buffer-size 30% --temporary-directory /data/amandeep/wikidataos-v2.1/wikidata_os_v5/parts/tempreal	0m1.699s
user	0m1.310s
sys	0m0.068s

**Comment by CraigMiloRogers** [comment]
Workaround: use `gzip`

**Comment by CraigMiloRogers** [comment]
The problem appears with pigz 2.3.4 running on centos 7.  centos 7 is old, with an old Linux kernel, and should be upgraded to a centos 8 release or another Linux release, such as Ubuntu (since CentOS itself is going away). I could not replicate the problem with the current version of pigz, pigz 2.4.
