### ISSUE TITLE
Error while running graph-embeddings

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#274]
command :
```
kgtk graph-embeddings -i wikidataos.for.text-embedding.tsv.gz -o wikidataos.for.text-embedding.graph-embeddings.tsv -T /tmp -ot w2v
```

Head of the file
```
id	node1	label	node2	rank	node2;wikidatatype
P10-P1628-32b85d-7927ece6-0	P10	P1628	"http://www.w3.org/2006/vcard/ns#Video"	normal	url
P10-P1628-acf60d-b8950832-0	P10	P1628	"https://schema.org/video"	normal	url
P10-P1629-Q34508-bcc39400-0	P10	P1629	Q34508	normal	wikibase-item
P10-P1659-P1651-c4068028-0	P10	P1659	P1651	normal	wikibase-property
P10-P1659-P18-5e4b9c4f-0	P10	P1659	P18	normal	wikibase-property
P10-P1659-P4238-d21d1ac0-0	P10	P1659	P4238	normal	wikibase-property
P10-P1659-P51-86aca4c5-0	P10	P1659	P51	normal	wikibase-property
P10-P1855-Q15075950-7eff6d65-0	P10	P1855	Q15075950	normal	wikibase-item
P10-P1855-Q69063653-c8cdb04c-0	P10	P1855	Q69063653	normal	wikibase-item
```

Error:
```
(kgtk-env) [root@ckg04 wikidata_os_v5]#  kgtk graph-embeddings -i wikidataos.for.text-embedding.tsv.gz -o wikidataos.for.text-embedding.graph-embeddings.tsv -T /tmp -ot w2v
/data/amandeep/Github/kgtk/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'NameError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
(kgtk-env) [root@ckg04 wikidata_os_v5]#  kgtk --debug graph-embeddings -i wikidataos.for.text-embedding.tsv.gz -o wikidataos.for.text-embedding.graph-embeddings.tsv -T /tmp -ot w2v
Traceback (most recent call last):
  File "/data/amandeep/Github/kgtk/kgtk/cli/graph_embeddings.py", line 379, in run
    kct.process()
  File "/data/amandeep/Github/kgtk/kgtk/cli/graph_embeddings.py", line 74, in process
    kw.file_out.seek(0)         # set the cursor to the top of the file
  File "/opt/miniconda3/envs/kgtk-env/lib/python3.7/gzip.py", line 371, in seek
    raise OSError('Negative seek in write mode')
OSError: Negative seek in write mode
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/amandeep/Github/kgtk/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/data/amandeep/Github/kgtk/kgtk/cli/graph_embeddings.py", line 464, in run
    raise KGTKException(str(e))
NameError: name 'KGTKException' is not defined
/data/amandeep/Github/kgtk/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'NameError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
```

**Comment by Bin-Go2** [comment]
If possible, could you please check the format of your input. It is pretty important since the code will first try to convert the input into the corresponding training set for graph embedding generation.

**Comment by Bin-Go2** [comment]
Thanks for your notification and this bug has been fixed. If any issues appear, please let me know :)

**Comment by szeke** [comment]
I see the same error when processing a `gz` file (attached). The command will read the file if it is uncompressed (and then hit a different error, which I will report in a separate issue)

[geinput.tsv.gz](https://github.com/usc-isi-i2/kgtk/files/5733411/geinput.tsv.gz)

**Comment by filievski** [comment]
AFAIK, this is now solved. Closing

**Comment by saggu** [comment]
I am seeing the exact same error as I reported in the beginning. I am trying to process a gzipped file. The error occurs while trying to `seek` in output mode

```
Traceback (most recent call last):
  File "/data/amandeep/Github/kgtk/kgtk/cli/graph_embeddings.py", line 391, in run
    kct.process()
  File "/data/amandeep/Github/kgtk/kgtk/cli/graph_embeddings.py", line 75, in process
    kw.file_out.seek(0)         # set the cursor to the top of the file
  File "/opt/miniconda3/envs/kgtk-env/lib/python3.7/gzip.py", line 371, in seek
    raise OSError('Negative seek in write mode')
OSError: Negative seek in write mode
```
