### ISSUE TITLE
Error importing 2018 Wikidata dumps

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#278]
**Describe the bug**
When importing wikidata dumps from 2018 (e.g., [20180820.json.gz](https://drive.google.com/file/d/1pdaxKEQ8wtfQk4PPxu5JqM0bjpJKoPGn/view?usp=sharing), but I have found others) I get some errors like the one below:
```
Exiting worker process 4 (pid 1474).
Process Process-8:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/multiprocess-0.70.11.1-py3.8.egg/multiprocess/process.py", line 297, i
n _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/site-packages/multiprocess-0.70.11.1-py3.8.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pyrallel.lib-0.0.9-py3.8.egg/pyrallel/parallel_processor.py", line 419, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/kgtk-0.5.0-py3.8.egg/kgtk/cli/import_wikidata.py", line 1212, in process
    enttype = val.get('entity-type')
AttributeError: 'str' object has no attribute 'get'
```
In most cases the import manages to end, but in some cases like the link provided above, all the workers exit, the MiB/s goes to 0 and the progress stops. if the process is aborted, the imported dump is missing several GB of data.

**To Reproduce**
1. Import wikidata with a 2018 dump such as 20180820.json.gz. Link: https://drive.google.com/file/d/1pdaxKEQ8wtfQk4PPxu5JqM0bjpJKoPGn/view?usp=sharing
2. Wait and see error (takes around 1h depending on your machine).

**Expected behavior**
The dump should be imported successfully.

**Comment by CraigMiloRogers** [comment]
Ad-hoc changes committed to `dev`. These changes fis this datafile, but we may expect other Wikidata JSON irregularities to cause crashes.
