### ISSUE TITLE
graph-embedding exceptions: RuntimeError: error executing torch_shm_manager 

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#279]
The following error happens when I try to run graph-embeddings as follows:
```
kgtk graph-embeddings --verbose -i "$TEMP"/ge/geinput.tsv \
-o "$TEMP"/ge/outputfile \
--retain_temporary_data True \
--operator translation \
--workers 1 \
--log "$TEMP"/ge/ge.log \
-T "$TEMP"/ge \
-ot w2v
```

With file 
[geinput.tsv.gz](https://github.com/usc-isi-i2/kgtk/files/5733428/geinput.tsv.gz)

The error on my MacBook Pro is (I have the latest from dev):
```
In Processing, Please go to /Users/pedroszekely/Downloads/kypher/temp.wikidata_os_v5/ge/ge.log to check details
Opening the input file: /Users/pedroszekely/Downloads/kypher/temp.wikidata_os_v5/ge/geinput.tsv
KgtkReader: File_path.suffix: .tsv
KgtkReader: reading file /Users/pedroszekely/Downloads/kypher/temp.wikidata_os_v5/ge/geinput.tsv
header: id	node1	label	node2
node1 column found, this is a KGTK edge file
KgtkReader: Special columns: node1=1 label=2 node2=3 id=0
KgtkReader: Reading an edge file.
Opening the output file: /Users/pedroszekely/Downloads/kypher/temp.wikidata_os_v5/ge/tmp_geinput.tsv
File_path.suffix: .tsv
KgtkWriter: writing file /Users/pedroszekely/Downloads/kypher/temp.wikidata_os_v5/ge/tmp_geinput.tsv
header: id	node1	label	node2
Processing the input records.
Processed 66997 records.
Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/cli/graph_embeddings.py", line 420, in run
    train(config, subprocess_init=subprocess_init)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torchbiggraph-1.0.0-py3.7.egg/torchbiggraph/train.py", line 938, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank, subprocess_init):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torchbiggraph-1.0.0-py3.7.egg/torchbiggraph/train.py", line 518, in train_and_report_stats
    model.share_memory()
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 1119, in share_memory
    return self._apply(lambda t: t.share_memory_())
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 1119, in <lambda>
    return self._apply(lambda t: t.share_memory_())
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/tensor.py", line 330, in share_memory_
    self.storage().share_memory_()
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/storage.py", line 118, in share_memory_
    self._share_filename_()
RuntimeError: error executing torch_shm_manager at "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/cli/graph_embeddings.py", line 465, in run
    raise KGTKException(str(e))
NameError: name 'KGTKException' is not defined
/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'NameError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
```

The log file: 
[ge.log](https://github.com/usc-isi-i2/kgtk/files/5733434/ge.log)

My output folder:
![image](https://user-images.githubusercontent.com/1074599/102962815-79900280-449c-11eb-88cf-b6560c249d80.png)

**Comment by Bin-Go2** [comment]
Hi, I think there is somthing wrong with the `-o "$TEMP"/ge/outputfile`,  indeed, our kgtk's output format is .tsv and I download your dataset and to run it. It works successfully.
Command is following: 
```
kgtk graph-embeddings --verbose -i geinput.tsv \
> -o output.tsv \
> --retain_temporary_data True \
> --operator translation \
> --workers 1 \
> --log ge.log \
> -T ge \
> -ot w2v \
> -e 10
```

![image](https://user-images.githubusercontent.com/45792483/102963295-911bbb00-449d-11eb-8ef5-876db3926520.png)

**Comment by Bin-Go2** [comment]
Oh, I just checked the repository and find maybe you are using the code from the master branch. Actually, I have updated the code to the dev branch, could you please try the dev version of the graph embedding codes. (I cannot directly update codes for a master branch.) Let me know if you have any problems.

**Comment by szeke** [comment]
I am on the `dev` branch:
```
(kgtk) D22ML-PSZEKELY:kgtk pedroszekely$ git status
On branch dev
Your branch is up to date with 'origin/dev'.
```

I ran the command you sent:
```
(kgtk) D22ML-PSZEKELY:ge pedroszekely$ kgtk graph-embeddings --verbose -i geinput.tsv -o output.tsv --retain_temporary_data True --operator translation --workers 1 --log ge.log -T ge -ot w2v -e 10
In Processing, Please go to ge.log to check details
Opening the input file: geinput.tsv
KgtkReader: File_path.suffix: .tsv
KgtkReader: reading file geinput.tsv
header: id	node1	label	node2
node1 column found, this is a KGTK edge file
KgtkReader: Special columns: node1=1 label=2 node2=3 id=0
KgtkReader: Reading an edge file.
Opening the output file: ge/tmp_geinput.tsv
File_path.suffix: .tsv
KgtkWriter: writing file ge/tmp_geinput.tsv
header: id	node1	label	node2
Processing the input records.
Processed 66997 records.
/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'NameError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
```

**Comment by Bin-Go2** [comment]
I think the possible reason could be the kgtk version, can you `cd` to the kgtk repository and run `pip install .` to reinstall the kgtk library and run the commands again? Since I saw the environment of yours is `kgtk-0.5.0-py3.7.egg`  and mine is 'kgtk                  0.4.0'

**Comment by szeke** [comment]
Same error after `pip install .`:
```
(kgtk) D22ML-PSZEKELY:ge pedroszekely$ kgtk --debug graph-embeddings --verbose -i geinput.tsv -o output.tsv --retain_temporary_data True --operator translation --workers 1 --log ge.log -T ge -ot w2v -e 10
In Processing, Please go to ge.log to check details
Opening the input file: geinput.tsv
KgtkReader: File_path.suffix: .tsv
KgtkReader: reading file geinput.tsv
header: id	node1	label	node2
node1 column found, this is a KGTK edge file
KgtkReader: Special columns: node1=1 label=2 node2=3 id=0
KgtkReader: Reading an edge file.
Opening the output file: ge/tmp_geinput.tsv
File_path.suffix: .tsv
KgtkWriter: writing file ge/tmp_geinput.tsv
header: id	node1	label	node2
Processing the input records.
Processed 66997 records.
Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/cli/graph_embeddings.py", line 420, in run
    train(config, subprocess_init=subprocess_init)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torchbiggraph-1.0.0-py3.7.egg/torchbiggraph/train.py", line 938, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank, subprocess_init):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torchbiggraph-1.0.0-py3.7.egg/torchbiggraph/train.py", line 518, in train_and_report_stats
    model.share_memory()
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 1119, in share_memory
    return self._apply(lambda t: t.share_memory_())
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/nn/modules/module.py", line 1119, in <lambda>
    return self._apply(lambda t: t.share_memory_())
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/tensor.py", line 330, in share_memory_
    self.storage().share_memory_()
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/storage.py", line 118, in share_memory_
    self._share_filename_()
RuntimeError: error executing torch_shm_manager at "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/torch-1.5.1-py3.7-macosx-10.9-x86_64.egg/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/cli/graph_embeddings.py", line 465, in run
    raise KGTKException(str(e))
NameError: name 'KGTKException' is not defined
/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'NameError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found

```

**Comment by Bin-Go2** [comment]
Could you please provide your conda environment?  From the debug, it seems that the error is not related to the code.

**Comment by szeke** [comment]
Let's move the conversation to slack

**Comment by szeke** [comment]
Problem caused by out of date tensor flow installation. Resolved.
