### ISSUE TITLE
lexicalize fails parsing label

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#281]
Running the new `lexicalize` command fails with the following exception. Looks like it chokes on the following line in the input file. The input file was written by kgs, so it is unexpected that it cannot parse the line:
```
P1088-label-en	P1088	label	'Mohs\\' hardness'@en
```

The command:
```
!$kgtk text-embedding -i $OUT/all.tsv.gz \
--embedding-projector-metadata-path none \
--label-properties label \
--isa-properties P31 P279 P452 P106 \
--description-properties description \
--property-value P186 P17 P127 P176 \
--has-properties "" \
-f kgtk_format \
--output-data-format kgtk_format \
--save-embedding-sentence \
--model bert-large-nli-cls-token \
-o "$TE" \
> "$TE"/text-embedding.tsv
```

The exception:
```
Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/cli/lexicalize.py", line 250, in run
    lexer.process_unsorted_input(kr, kw, add_entity_labels=add_entity_labels_from_input)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/gt/lexicalize_utils.py", line 365, in process_unsorted_input
    if self.add_entity_if_label(node_id, row[kr.label_column_idx], row[kr.node2_column_idx], self.label_properties):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/gt/lexicalize_utils.py", line 107, in add_entity_if_label
    self.add_entity_label(node_id, node_label)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/gt/lexicalize_utils.py", line 75, in add_entity_label
    text, language, language_suffix = KgtkFormat.destringify(node_label)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/kgtkformat.py", line 136, in destringify
    return (ast.literal_eval(s), language, language_suffix)
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    'Mohs\\' hardness'
                    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk/lib/python3.7/site-packages/kgtk/cli/lexicalize.py", line 255, in run
    raise KGTKException(str(e))
kgtk.exceptions.KGTKException: invalid syntax (<unknown>, line 1)
invalid syntax (<unknown>, line 1)
        0.50 real         0.29 user         0.09 sys
```

**Comment by CraigMiloRogers** [comment]
It looks to me like the input is buggy.
```'Mohs\\' hardness'@en```
should be
```'Mohs\' hardness'@en```

**Comment by CraigMiloRogers** [comment]
@szeke  What is `kgs`?

**Comment by szeke** [comment]
@CraigMiloRogers I don't understand the question re `kgs`

Also, the buggy label was produced by the wikidata import.

**Comment by thadguidry** [comment]
Looks like there was some problem on the `en` (English) label parsing?
Here's the original English label and aliases to understand where the parsing is getting things wrong in regards to
 `Mohs' hardness` where perhaps the single quote `'` or the `s'` was escaped incorrectly, since `\\` is a typical escape sequence such as in Java and Javascript:
![image](https://user-images.githubusercontent.com/986438/103579852-b72e5b80-4e9e-11eb-845d-427c944dd681.png)

**Comment by CraigMiloRogers** [comment]
@szeke How was your `all.tsv.gz` file created?  I'd like to trace the fault backward.

**Comment by szeke** [comment]
The files are the products of https://github.com/usc-isi-i2/kgtk/blob/dev/tutorial/2%20Construct%20KG.ipynb 
The partition command is in https://github.com/usc-isi-i2/kgtk/blob/dev/tutorial/3%20Partition%20KG.ipynb
