### ISSUE TITLE
`kgtk compact` Failing

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#359]
Traceback (most recent call last):
  File "/opt/miniconda3/envs/kgtk-env/bin/kgtk", line 33, in <module>
    sys.exit(load_entry_point('kgtk', 'console_scripts', 'kgtk')())
  File "/data/amandeep/Github/kgtk/kgtk/cli_entry.py", line 311, in cli_entry
    ret_code = cli_entry_sequential_commands(args, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/data/amandeep/Github/kgtk/kgtk/cli_entry.py", line 235, in cli_entry_sequential_commands
    ret_code = cli_entry_pipe(commands, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/data/amandeep/Github/kgtk/kgtk/cli_entry.py", line 112, in cli_entry_pipe
    mod.add_arguments_extended(sub_parser, parsed_shared_args)
  File "/data/amandeep/Github/kgtk/kgtk/cli/compact.py", line 42, in add_arguments_extended
    _command: str = parsed_shared_args._command
AttributeError: 'Namespace' object has no attribute '_command'

**Comment by CraigMiloRogers** [comment]
The code that sets parsed_shared_args._command appears to have been lost. Perhaps I misedited a merge.

**Comment by CraigMiloRogers** [comment]
Code to set  parsed_shared_args._command has been merged into `dev`.
