### ISSUE TITLE
Import wikidata bug

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#377]
Note: the import works, but I see an exception:

Dump [20210104.json.gz](https://drive.google.com/file/d/1c_yqDmM5qsKF64Ix9MSDKuAwnbRAcnjD/view?usp=sharing) I am seeing the following exception:

```
Opening the qual file in the qual collector with KgtkWriter: 20210104/qualfile.tsv
Start parallel processing
Starting worker process 0 (pid 62).
Starting worker process 1 (pid 63).
Starting worker process 2 (pid 64).
Starting worker process 3 (pid 65).
Starting worker process 4 (pid 66).
Starting worker process 5 (pid 67).
Exiting worker process 0 (pid 62).
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/multiprocess-0.70.11.1-py3.8.egg/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/site-packages/multiprocess-0.70.11.1-py3.8.egg/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pyrallel.lib-0.0.10-py3.8.egg/pyrallel/parallel_processor.py", line 465, in _run
    result = mapper.process(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/kgtk-0.5.0-py3.8.egg/kgtk/cli/import_wikidata.py", line 1848, in process
    len(invalid_erows) > 0 or \
TypeError: object of type 'NoneType' has no len()
```
The command I am using is the following:
```
kgtk  --debug --timing --progress import-wikidata \
        -i $line \
        --node ${TEMPDIR}/nodefile.tsv \
        --edge ${TEMPDIR}/edgefile.tsv \
        --qual ${TEMPDIR}/qualfile.tsv \
        --use-mgzip-for-input True \
        --use-mgzip-for-output True \
        --use-shm True \
        --procs 6 \
        --mapper-batch-size 5 \
        --max-size-per-mapper-queue 3 \
        --deprecated \
        --single-mapper-queue True \
        --collect-results True \
        --collect-seperately True\
        --collector-batch-size 10 \
        --collector-queue-per-proc-size 3 \
        --progress-interval 500000 --fail-if-missing False
```

**Comment by CraigMiloRogers** [comment]
Added tests yo prevent this.
