### ISSUE TITLE
path command throws exception

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#383]
The path command throws the following exception on a large file. Listing the exception here as it may be possible to fix it by looking at the code. Replicating is hard because it requires large files:

```
Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk-env/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/cli/paths.py", line 130, in run
    tgt: str = path_row[path_target_idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk-env/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/pedroszekely/opt/anaconda3/envs/kgtk-env/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/cli/paths.py", line 213, in run
    raise KGTKException('Error: ' + str(e))
kgtk.exceptions.KGTKException: Error: list index out of range
Error: list index out of range
```

**Comment by saggu** [comment]
@szeke this looks specific to the `path` file specified, which has the pairs of qnodes to find a path between. Could you post that file?

**Comment by szeke** [comment]
@saggu I can try to get the files later, there is no obvious thing about failing to handle an edge case?

**Comment by saggu** [comment]
This case: There is a row in the file which has different number of columns than other rows. 

The code should throw an exception, just the message needs to be clear
