### ISSUE TITLE
ShmQueue Reported Open Queue on Worker process Shutdown in import-wikidata

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#385]
Telling the workers to shut down.
Waiting for the workers to shut down.
Exiting worker process 2 (pid 7270).
Exiting worker process 15 (pid 7300).
Exiting worker process 16 (pid 7301).
Exiting worker process 1 (pid 7266).
Exiting worker process 9 (pid 7294).
Exiting worker process 0 (pid 7261).
Exiting worker process 5 (pid 7287).
Exiting worker process 10 (pid 7295).
Exiting worker process 14 (pid 7299).
Exiting worker process 7 (pid 7292).
Exiting worker process 4 (pid 7283).
Exiting worker process 12 (pid 7297).
Exiting worker process 8 (pid 7293).
Exiting worker process 13 (pid 7298).
Exiting worker process 3 (pid 7276).
Exiting worker process 6 (pid 7291).
Exiting worker process 11 (pid 7296).
Traceback (most recent call last):===============================================================================================================>] 100% ETA 0:00:00
  File "/nas/home/rogers/kgtk/github/kgtk/kgtk/cli/import_wikidata.py", line 2912, in run
    pp.join()
  File "/nas/home/rogers/.conda/envs/kgtk-env/lib/python3.8/site-packages/pyrallel/parallel_processor.py", line 389, in join
    q.join_thread()
  File "/nas/home/rogers/.conda/envs/kgtk-env/lib/python3.8/multiprocessing/queues.py", line 146, in join_thread
    assert self._closed, "Queue {0!r} not closed".format(self)
AssertionError: Queue <pyrallel.queue.ShmQueue object at 0x7efe0c08aca0> not closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas/home/rogers/kgtk/github/kgtk/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/nas/home/rogers/kgtk/github/kgtk/kgtk/cli/import_wikidata.py", line 3028, in run
    raise KGTKException(str(e))
kgtk.exceptions.KGTKException: Queue <pyrallel.queue.ShmQueue object at 0x7efe0c08aca0> not closed

**Comment by CraigMiloRogers** [comment]
There is a bug in pyrallel-lib 0.0.10 that was not present in pyrallel-lib 0.0.9.

**Comment by CraigMiloRogers** [comment]
I changed requirements-full.txt to specify pyrallel-lib 0.0.9.
