### ISSUE TITLE
cli branch unable to be used now because of import error

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/kgtk#4]
When calling any kgtk cli function, it will raise an error because of import error
```
(gpt2) ➜  kgtk git:(feature/cli) ✗ kgtk dummy 
Traceback (most recent call last):
  File "/Users/minazuki/miniconda3/envs/gpt2/bin/kgtk", line 11, in <module>
    load_entry_point('kgtk', 'console_scripts', 'kgtk')()
  File "/Users/minazuki/Desktop/studies/master/2018Summer/DSBOX_2019/kgtk/kgtk/cli_entry.py", line 70, in cli_entry
    mod = importlib.import_module('.{}'.format(h), 'kgtk.cli')
  File "/Users/minazuki/miniconda3/envs/gpt2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/minazuki/Desktop/studies/master/2018Summer/DSBOX_2019/kgtk/kgtk/cli/wikidata_nodes_import.py", line 46
    from __future__ import unicode_literals
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
(gpt2) ➜  kgtk git:(feature/cli) ✗ 
```

**Comment by naren954** [comment]
I removed the header.
