### ISSUE TITLE
error running kgtk generate_mediawiki_jsons command

### ISSUE THREAD

**Issue by ZhiqiangJerryQiu** [usc-isi-i2/kgtk#400]
Similar to issue #399, I hope to generate a jsonl file from kgtk file.
The command I use is
```
kgtk cat -i moz_re_test.tsv moz_re_test.tsv | pv | kgtk generate_mediawiki_jsons -pd yes --debug -n 1000000 -pr moz_re_test
```
I received the following error message:
```
Traceback (most recent call last):
  File "/nas/home/zqiu/kgtk/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/nas/home/zqiu/kgtk/kgtk/cli/generate_mediawiki_jsons.py", line 188, in run
    has_rank = has_rank
  File "/nas/home/zqiu/kgtk/kgtk/generator.py", line 584, in __init__
    self.error_action = kwargs.pop('error_action')
KeyError: 'error_action'
/nas/home/zqiu/kgtk/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'KeyError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
```

Let me know if more information is needed.

**Comment by saggu** [comment]
@ZhiqiangJerryQiu if you just want to convert kgtk edge file to json lines, you should use kgtk cat

```
kgtk cat -i moz_re_test.tsv moz_re_test.tsv -o moz.jl --output-format jsonl-map
```

Unless you have some other usecase

**Comment by CraigMiloRogers** [comment]
There are lots of problems with the code. I made some significant rewrites.  Here's my test command:

```kgtk --debug generate_mediawiki_jsons -n 10000 -i ~/moz_re_test.tsv -pf ~/moz_re_test.tsv -fp -ip -v```

**Comment by CraigMiloRogers** [comment]
TODO: update the documentation.

**Comment by CraigMiloRogers** [comment]
The code changes (but not the .md file) have been pushed into `dev`.
