### ISSUE TITLE
"Qualifier edge with no preceeding statement" while there is preceeding statement.

### ISSUE THREAD

**Issue by ZhiqiangJerryQiu** [usc-isi-i2/kgtk#449]
**Describe the bug**
When I run
`kgtk generate_wikidata_triples -i $KGTK_FILE -pf $PROPERTY_FILE -o $TTL_FILE --debug`
I received the following error:
```
Traceback (most recent call last):
  File "/nas/home/zqiu/kgtk/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/nas/home/zqiu/kgtk/kgtk/cli/generate_wikidata_triples.py", line 200, in run
    generator.process()
  File "/nas/home/zqiu/kgtk/kgtk/generator.py", line 227, in process
    self.entry_point(input_row_count, row)
  File "/nas/home/zqiu/kgtk/kgtk/generator.py", line 586, in entry_point
    node1, prop, node2, is_qualifier_edge, e_id, line_number)
  File "/nas/home/zqiu/kgtk/kgtk/generator.py", line 528, in generate_normal_triple
    raise KGTKException("Qualifier edge with no preceeding statement at line %d: (%s, %s, %s)" % (line_number, repr(node1), repr(property), repr(node2)))
kgtk.exceptions.KGTKException: Qualifier edge with no preceeding statement at line 72020: ('V00_72017', 'P1181', '0.5011')
Qualifier edge with no preceeding statement at line 72020: ('V00_72017', 'P1181', '0.5011')
```
while the data at around line 72020 looks like:
```
Q00_Paper_2515_DesignQuality	P31	macroscore:DesignQuality	V00_72016
Q00_Paper_2515_DesignQuality	label	'XXX'@en	V00_72017
V00_72017	P1181	0.5011	V00_72018
```
I've shared the full dataset with @saggu privately.

**Comment by szeke** [comment]
Assigning to @saggu for now as @CraigMiloRogers is out on vacation and sounds like this is urgent

**Comment by saggu** [comment]
I was able to run this command successfully using the 3 lines posted here. I have suggestions and questions.

Question: why does your `label` edge have a qualifier?

Suggestion: create ids using `kgtk add-id` and `--id-style wikidata` option.

Add option `--output-n-lines` and set it to a large values (1000000) for example.

Try to run this again and see if it fixes your issue as a workaround. There could be a bug in the code around the Qnode edge boundary which will take more time to resolve.
