### ISSUE TITLE
mgzip Shutdown Bug

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#467]
Occasionally, but repeatably, `kgtk filter` can get mgzip shutdown failures:
```
181% time kgtk --debug ${KGTK_OPTIONS} filter ${MGZIP_OPTIONS} -i ${WORKING_FOLDER}/FactSet_all_plus.tsv.gz -p ';alias;' -o ${WORKING_FOLDER}/aliases.tsv.gz -p ';description;' -o ${WORKING_FOLDER}/descriptions.tsv.gz -p ';label;' -o ${WORKING_FOLDER}/labels.tsv.gz -p ';count_distinct_properties,datatype;' -o ${WORKING_FOLDER}/metadata.tsv.gz --reject-file ${WORKING_FOLDER}/claims_and_quals.tsv.gz | & tee ${WORKING_FOLDER}/filter.log
Exception ignored in: <function Pool.__del__ at 0x7f965c9c0280>                                                                                                        
Traceback (most recent call last):                                                                                                                                     
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 268, in __del__                                                                                            
    self._change_notifier.put(None)                                                                                                                                    
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put                                                                                              
    self._writer.send_bytes(obj)                                                                                                                                       
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function Pool.__del__ at 0x7f965c9c0280>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function Pool.__del__ at 0x7f965c9c0280>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
182%

**Comment by CraigMiloRogers** [comment]
https://github.com/vinlyx/mgzip/issues/13

**Comment by CraigMiloRogers** [comment]
The error messages shown above indicated the possibility that data at the end of the file wasn't being written before the fd was closed.  However, a comparison between files produced with mgzip and gzip showed that no data had been lost.

**Comment by CraigMiloRogers** [comment]
I tried several approaches to prevent the bad file descriptor messages, but none of them worked.

**Comment by CraigMiloRogers** [comment]
Unless I want to experiment with mgzip itself, perhaps fork the code into a usc-isi-i2 project, there's nothing more that I can think to do at present.

**Comment by CraigMiloRogers** [comment]
I reopened this because the error messages are present and something must be done.

**Comment by CraigMiloRogers** [comment]
This issue must be addressed, because the error messages are highly likely to distress our users, and performance is poorer without mgzip.

This is likely to take time.

We may need to fork the official repository, apply changes, and wait for an official solution.

**Comment by CraigMiloRogers** [comment]
I forked the `mgzip` repository, applied a one-line change (close the multiprocessing pool), and uploaded a new repository: `usc-isi-i2-mgzip`.

**Comment by CraigMiloRogers** [comment]
I updated `requirements-full.txt` in `dev` to require the corrected versin of mgzip.

**Comment by timhughes** [comment]
@CraigMiloRogers we created a fork of mgzip over at https://github.com/pgzip/pgzip to coordinate new releases and patches. I am usually able to look at issues and PRs within a week or two. We are releasing as pgzip on pypi and have incorporated the pool close fix.
