### ISSUE TITLE
Unit tests are Failing

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#534]
Unit tests are failing.

**Comment by CraigMiloRogers** [comment]
```
======================================================================
FAIL: test_kgtk_cat_two_files (test_cat.TestKGTKCat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nas/home/rogers/kgtk/github/kgtkut/tests/test_cat.py", line 97, in test_kgtk_cat_two_files
    self.assertEqual(len(df), 6)
AssertionError: 5 != 6
```

The two input files are:
```
sample_kgtk_edge_Q47158.tsv
sample_kgtk_edge_file_with_id.tsv
```

The last line in each input file did not end in a line ending sequence (newline). This is a violation of the KGTK File Specification v2, which requires that all lines in a KGTK file must end in an end-of-line character or sequence.

The cure was to add final newlines to each file.

**Comment by CraigMiloRogers** [comment]
```
======================================================================
FAIL: test_graph_embeddings_format_kgtk (test_graph_embeddings.TestGraphEmbeddings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nas/home/rogers/kgtk/github/kgtkut/tests/test_graph_embeddings.py", line 48, in test_graph_embeddings_format_kgtk
    self.assertTrue(value[1]=='graph_embeddings')
AssertionError: False is not true

```
This code failed because it assumed that a KGTK format file did not have a header line.  The code was corrected to expect a header line at the start of a KGTK format file.

**Comment by CraigMiloRogers** [comment]
We asked for python 3.8, but the system $CONDA is configured for python 3.9!

From the later `pip` step:
```
Requirement already satisfied: pip in /usr/share/miniconda/lib/python3.9/site-packages (21.1.3)
```

**Comment by CraigMiloRogers** [comment]
The next run still failed:
```
FAIL: test_triple_small_values (test_triple_generation.TestTripleGeneration)
1      rg:en_fawn  /r/Synonym  ...     RG      NaN
----------------------------------------------------------------------
2      rg:en_fawn  /r/Synonym  ...     RG      NaN
Traceback (most recent call last):
3      rg:en_fawn  /r/Synonym  ...     RG      NaN
  File "/home/runner/work/kgtk/kgtk/tests/test_triple_generation.py", line 131, in test_triple_small_values
4      rg:en_fawn  /r/Synonym  ...     RG      NaN
    self.assertEqual(f1.readlines(), f2.readlines())
AssertionError: Lists differ: ['@pr[2297 chars]7079 1.9860001065575846E-7 ;\n', '    wdt:P708[2645 chars]'\n'] != ['@pr[2297 chars]7079 0.00000019860001065575846 ;\n', '    wdt:[2657 chars]'\n']

First differing element 37:
'    wdt:P7079 1.9860001065575846E-7 ;\n'
'    wdt:P7079 0.00000019860001065575846 ;\n'

Diff is 5766 characters long. Set self.maxDiff to None to see it.

**Comment by CraigMiloRogers** [comment]
The reason they are formatted differently is that TripleGenerator uses ETK which encapsulates the numbers (as strings) into an rdflib format.  rdflib, in term.py, converts the nmber strings into Decimal numbers.  When the Decimal numbers are converted back to string for output, they are sometimes formatted in scientific notation.  If we edited rdflib, we could force the numbers to always be represented in scientific notation (or the engineering variant), but there's no way to force the numbers to be represented without exponents, and there are no rules listed governing when an exponent representation will be used.

**Comment by CraigMiloRogers** [comment]
On third thought: what if we have two reference files, covering the two alternative output formats for the one item?

**Comment by CraigMiloRogers** [comment]
The two reference file approach is working.
