### ISSUE TITLE
Coveralls Failed

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#539]
```
Run coverallsapp/github-action@master
/home/runner/work/_actions/coverallsapp/github-action/master/lib/run.js:97
                        throw new Error('Parallel webhook error:' + err + ', ' + JSON.stringify(data));
                        ^

Error: Parallel webhook error:Error: {"error":"Invalid github token"}, {"error":"Invalid github token"}
    at Request._callback (/home/runner/work/_actions/coverallsapp/github-action/master/lib/run.js:97:31)
    at Request.self.callback (/home/runner/work/_actions/coverallsapp/github-action/master/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/runner/work/_actions/coverallsapp/github-action/master/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/coverallsapp/github-action/master/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by CraigMiloRogers** [comment]
According to GitHub's documentation, this shouldn't happen.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by CraigMiloRogers** [comment]
@saggu fixed the code.  Changes were merged into `dev`.
