### ISSUE TITLE
 The 'redis' distribution was not found and is required by kgtk

### ISSUE THREAD

**Issue by ZhiqiangJerryQiu** [usc-isi-i2/kgtk#592]
bash script
```
export GRAPHS="./graphs"
export WORKING_FOLDER="./temp"

echo -e "\n*** Sort the claims and qualifiers file on the id column: ***"
time kgtk ${KGTK_OPTIONS} graph-statistics ${GZIP_CMD} ${MGZIP_OPTIONS} \
    -i ${GRAPHS}/claims.tsv.gz \
    -o ${GRAPHS}/metadata.pagerank.undirected.tsv.gz \
    --compute-pagerank True \
    --compute-hits False \
    --page-rank-property Pundirected_pagerank \
    --use-mgzip True \
    --mgzip-threads 12 \
    --output-degrees False \
    --output-pagerank True \
    --output-hits False \
    --output-statistics-only \
    --undirected True \
    --log-file ${WORKING_FOLDER}/metadata.pagerank.undirected.summary.txt
```

Error:
```
Traceback (most recent call last):
  File "/nas/home/zqiu/.local/bin/kgtk", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'redis' distribution was not found and is required by kgtk
```

**Comment by saggu** [comment]
What is the python version? Seems like you have `3.6`, recommended is `3.9`

Also, list all the options being used, you do not need GZIP_CMD and MGZIP_OPTIONS

**Comment by ZhiqiangJerryQiu** [comment]
I was using Python 3.9.

**Comment by ZhiqiangJerryQiu** [comment]
Thanks. The problem was I didn’t install pip under my new conda environment (which is python==3.9.7). When I do pip install kgtk, it uses the pip from my base environment. 

Then, when I run kgtk command, there was no kgtk package install in my current conda environment, conda would then look into my base environment and find the kgtk there which is under python==3.6.

Wrong command to setup environment:
```
conda create -n kgkt-browser python==3.9
pip install kgtk==1.1.0
<kgtk command>
```

Instead, I should do:
```
conda create -n kgkt-browser python==3.9
conda install pip
pip install kgtk==1.1.0
<kgtk command>
```

**Comment by saggu** [comment]
or `pip install --update pip`, have to keep your python virtual environments up to date
