### ISSUE TITLE
Exception in class visualization code for qnode: Q11575

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#603]
```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/kgtk/kgtk/visualize/visualize_api.py", line 490, in compute_visualization_graph
    size_value = self.node_size_minimum + (log_cur - log_min) * (
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 342, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 374, in handle_one_request
    self.run_wsgi()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 353, in __call__
    return self._app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/src/kgtk_browser_app.py", line 276, in get_class_graph_data
    visualization_graph, _ = kv.compute_visualization_graph()
  File "/kgtk/kgtk/visualize/visualize_api.py", line 510, in compute_visualization_graph
    raise KGTKException(str(e))
kgtk.exceptions.KGTKException: float division by zero
```

**Comment by saggu** [comment]
[Q11575.zip](https://github.com/usc-isi-i2/kgtk/files/7901050/Q11575.zip)
 Command to reproduce:

```
kgtk visualize-force-graph -i Q11575.graph.edge.tsv --node-file Q11575.graph.node.tsv --direction arrow --node-size-column instance_count --node-size-minimum 2 --node-size-maximum 8.0 --node-size-default 5 --node-size-scale log --node-color-column node_type --node-color-style categorical --node-categorical-scale d3.schemeCategory10 --edge-color-column edge_type --edge-color-style categorical --edge-categorical-scale d3.schemeAccent --node-file-id node1 --tooltip-column tooltip --text-node above -o browser_tooltip/Q11575.graph.low.html
```
