### ISSUE TITLE
`filter_batch_size` is not defined

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#660]
The command add-labels seems broken. Whatever kgtk result i try to pipe to it, i get the error name 'filter_batch_size' is not definedCould you pls take a look?
Full debug info:

[2022-07-18 17:22:43 query]: SQL Translation:
---------------------------------------------
  SELECT graph_3_c1."node1" "_aLias.memeid", graph_7_c2."label" "_aLias.property", graph_7_c2."node2" "_aLias.value", graph_2_c3."node2" "_aLias.meme_label"
     FROM graph_2 AS graph_2_c3
     INNER JOIN graph_3 AS graph_3_c1, graph_7 AS graph_7_c2
     ON graph_3_c1."node1" = graph_2_c3."node1"
        AND graph_3_c1."node1" = graph_7_c2."node1"
        AND graph_2_c3."label" = ?
        AND graph_3_c1."label" = ?
        AND graph_3_c1."node2" = ?
  PARAS: ['label', 'P31', 'Q2927074']
---------------------------------------------
Traceback (most recent call last):
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/cli/lift.py", line 468, in run
    kl.process()
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/lift/kgtklift.py", line 1151, in process
    self.process_in_memory(ikr, lkr, urkw, mlkw, ulkw)
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/lift/kgtklift.py", line 690, in process_in_memory
    labels, _ = self.load_labels(lkr, self.label_file_path, save_input=False, labels_needed=labels_needed, label_rows=label_rows, is_label_file=True)
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/lift/kgtklift.py", line 293, in load_labels
    for row in kr:
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/io/kgtkreader.py", line 1448, in __next__
    return self.nextrow()
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/io/graphcacheadaptor.py", line 378, in nextrow
    reader_self.start_query(adapter_self.table_name,
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/io/graphcacheadaptor.py", line 620, in start_query
    query, parameters = self.build_query(table_name, column_names, verbose=verbose, very_verbose=very_verbose)
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/io/graphcacheadaptor.py", line 575, in build_query
    col_values: typing.List[str] = self.input_filter_lists[idx][col_state:(col_state+filter_batch_size)]
NameError: name 'filter_batch_size' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/exceptions.py", line 70, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/filipilievski/opt/anaconda3/envs/wikiEnv/lib/python3.8/site-packages/kgtk/cli/lift.py", line 475, in run
    raise KGTKException(str(e))
kgtk.exceptions.KGTKException: name 'filter_batch_size' is not defined
name 'filter_batch_size' is not defined

**Comment by CraigMiloRogers** [comment]
I think that this has been fixed in `dev`,  although I don't have unit tests for the various branches in the code.
