### ISSUE TITLE
ImportError during unit test

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/kgtk#667]
I create an unit test, `test_graph_statistics.py`, for the `kgtk graph-statistics` command in branch `graph-stat-betweenness`.

This unit test runs fine by itself, but it fails with ImportError if it runs after either `test_embedding.py` or `test_graph_embeddings.py`

I not sure what is going. The embedding test files must be loading incompatible library files?

```
$ python -m unittest -v test_embedding.py test_graph_statistics.py
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  7.97it/s]
ok
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  7.95it/s]
ok
test_undirected_betweenness (test_graph_statistics.TestKGTKGraphStatistics) ... test_undirected_betweenness:  /tmp/tmpf73g3id8
test_undirected_betweenness:  kgtk graph-statistics -i data/graph_statistics_zacharys_karate_club.tsv -o /tmp/tmpf73g3id8/graph_statistics_undirected.tsv --log-file /tmp/tmpf73g3id8/summary.txt --undirected True --compute-betweenness
Traceback (most recent call last):
  File "/home/ktyao/dev/kgtk/kgtk/exceptions.py", line 71, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/home/ktyao/dev/kgtk/kgtk/cli/graph_statistics.py", line 189, in run
    from graph_tool import centrality
  File "/home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/graph_tool/dl_import.py", line 58, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: /home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/graph_tool/libgraph_tool_core.s\
o)
/home/ktyao/dev/kgtk/kgtk/exceptions.py:91: UserWarning: Please raise KGTKException instead of <class 'ImportError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
```

**Comment by kyao** [comment]
Looks like there is incompatibility between pytorch and graph_tool

```
(kgtk-env) ktyao:~/dev/finsec/finsec-knowledge-graph/notebook$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from graph_tool import centrality
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/graph_tool/dl_import.py", line 58, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: /home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /home/kty\ao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/graph_tool/libgraph_tool_core.so)
>>> exit()
(kgtk-env) ktyao:~/dev/finsec/finsec-knowledge-graph/notebook$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from graph_tool import centrality
>>> import torch
>>> exit()
```

**Comment by kyao** [comment]
Using strace I found that pytorch load its own libgomp library:

pytorch: /home/ktyao/anaconda3/envs/kgtk-env/lib/python3.9/site-packages/torch/lib/libgomp-a34b32\33.so.1
versus
graph_tool:  /home/ktyao/anaconda3/envs/kgtk-env/lib/libgomp.so.1

**Comment by kyao** [comment]
The problem goes away if graph_tool is loaded first. Pytorch can use graph_tool's version  libgomp, but not vice versa.

This problem does not occur in kgtk pipelines, because each stage of the pipe runs in its own shell.

Fixed the problem by rename the unit test file so that the graph_tool test runs before pythorch test.

Closing the issue for now.
