### ISSUE TITLE
Unit Test failures in Triple Generation

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#668]
Running unit tests on my home workstation reveals errors in some triple generation tests:

```
======================================================================
FAIL: test_not_truthy_qnode_triple_generation (test_triple_generation.TestTripleGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/kgtk/github/kgtk-dev/tests/test_triple_generation.py", line 111, in test_not_truthy_qnode_triple_generation
    self.assertEqual(f1_lines, f2_lines)
AssertionError: Lists differ: ['@pr[1646 chars]    skos:prefLabel "A quantitative test to est[8093 chars]'\n'] != ['@pr[1646 chars]    schema:name "A quantitative test to estima[8093 chars]'\n']

First differing element 26:
'    skos:prefLabel "A quantitative test to est[138 chars] ;\n'
'    schema:name "A quantitative test to estima[135 chars] ;\n'

Diff is 10803 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_property_triple_generation (test_triple_generation.TestTripleGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/kgtk/github/kgtk-dev/tests/test_triple_generation.py", line 65, in test_property_triple_generation
    self.assertEqual(f1.readlines(), f2.readlines())
AssertionError: Lists differ: ['@pr[1488 chars]'    wikibase:claim p:P10 ;\n', '    wikibase:[5021 chars]'\n'] != ['@pr[1488 chars]'    schema:description "relevant video. For i[5021 chars]'\n']

First differing element 26:
'    wikibase:claim p:P10 ;\n'
'    schema:description "relevant video. For i[106 chars] ;\n'

Diff is 7364 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_truthy_property_triple_generation (test_triple_generation.TestTripleGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/kgtk/github/kgtk-dev/tests/test_triple_generation.py", line 43, in test_truthy_property_triple_generation
    self.assertEqual(f1.readlines(), f2.readlines())
AssertionError: Lists differ: ['@pr[1488 chars]'    wikibase:claim p:P10 ;\n', '    wikibase:[5513 chars]'\n'] != ['@pr[1488 chars]'    schema:description "relevant video. For i[5513 chars]'\n']

First differing element 26:
'    wikibase:claim p:P10 ;\n'
'    schema:description "relevant video. For i[106 chars] ;\n'

Diff is 7892 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_truthy_qnode_triple_generation (test_triple_generation.TestTripleGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/rogers/kgtk/github/kgtk-dev/tests/test_triple_generation.py", line 86, in test_truthy_qnode_triple_generation
    self.assertEqual(f1.readlines(), f2.readlines())
AssertionError: Lists differ: ['@pr[1646 chars]    skos:prefLabel "A quantitative test to est[9133 chars]'\n'] != ['@pr[1646 chars]    schema:name "A quantitative test to estima[9133 chars]'\n']

First differing element 26:
'    skos:prefLabel "A quantitative test to est[138 chars] ;\n'
'    schema:name "A quantitative test to estima[135 chars] ;\n'

Diff is 11870 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 182 tests in 128.926s

FAILED (failures=4)

**Comment by saggu** [comment]
Fixed in the commit dadeff565aaa8fc4c065a567b11dca32f4ae2b65 Issue was with RDFLIB releasing a new version which breaks triple generation
