### ISSUE TITLE
`kgtk` Command Fails If No Subcommand

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#676]
(kgtk-dev) 142% kgtk
Traceback (most recent call last):
  File "/home/rogers/miniconda3/envs/kgtk-dev/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rogers/miniconda3/envs/kgtk-dev/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rogers/kgtk/github/kgtk-dev/kgtk/__main__.py", line 5, in <module>
    sys.exit(cli_entry())
  File "/home/rogers/kgtk/github/kgtk-dev/kgtk/cli_entry.py", line 434, in cli_entry
    ret_code = cli_entry_sequential_commands(args, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/home/rogers/kgtk/github/kgtk-dev/kgtk/cli_entry.py", line 330, in cli_entry_sequential_commands
    ret_code = cli_entry_pipe(commands, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/home/rogers/kgtk/github/kgtk-dev/kgtk/cli_entry.py", line 294, in cli_entry_pipe
    return cli_single_command(args, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/home/rogers/kgtk/github/kgtk-dev/kgtk/cli_entry.py", line 127, in cli_single_command
    cmd_name = cmd_args[0].replace("_", "-")
IndexError: list index out of range

**Comment by CraigMiloRogers** [comment]
Let's assume a default subcommand of "no-command", which will generage:
```
(kgtk-dev) 150% kgtk
usage: kgtk [options] command [ / command]*
kgtk: error: argument command: invalid choice: 'no-command' (choose from 'add-id', 'build-kgtk-search-input', 'calc', 'cat', 'clean-data', 'community-detection', 'compact', 'deduplicate', 'connected-components', 'convert-embeddings-format', 'count', 'wc', 'expand', 'explode', 'denormalize_node2', 'export-gt', 'export-neo4j', 'export-wikidata', 'extract-wikidata-json', 'filter', 'generate-mediawiki-jsons', 'generate-wikidata-triples', 'graph-embeddings', 'graph-statistics', 'head', 'html', 'ifempty', 'ifexists', 'ifnotempty', 'ifnotexists', 'implode', 'import-atomic', 'import-concept-pairs', 'import-conceptnet', 'import-framenet', 'import-ntriples', 'import-visualgenome', 'import-wikidata', 'import-wordnet', 'join', 'lexicalize', 'lift', 'add-labels', 'md', 'normalize', 'lower', 'normalize-edges', 'normalize-nodes', 'paths', 'query', 'reachable-nodes', 'remove-columns', 'rename-columns', 'reorder-columns', 'select-columns', 'replace-nodes', 'sample', 'sort', 'sort2', 'split', 'table', 'tail', 'tee', 'text-embedding', 'unique', 'unreify-rdf-statements', 'unreify-values', 'validate-properties', 'filter-properties', 'validate', 'visualize-graph', 'zconcat')
(kgtk-dev) 151%
```

**Comment by CraigMiloRogers** [comment]
Merged into `dev`.

**Comment by CraigMiloRogers** [comment]
Documentation? Unit test?
