### ISSUE TITLE
KGTKException on graph_statistics

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk#689]
**Describe the bug**
I've received a **KGTKException** while reuning kgtk **graph_statistics**

**To Reproduce**

export GRAPH_STEP1=/app/kgtk/data/aux-tsv/step1-claims.tsv.gz

...$ kgtk graph_statistics -i $GRAPH_STEP1 --log-file step1-claims.stat --output-statistics-only --compute-pagerank False --compute-hits False --output-degrees False
/app/kgtk/miniconda3/lib/python3.9/site-packages/kgtk/exceptions.py:90: UserWarning: Please raise KGTKException instead of <class 'ModuleNotFoundError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found

...$ kgtk graph_statistics -i $GRAPH_STEP1 --log-file step1-claims.stat --output-statistics-only --compute-pagerank False --compute-hits False
/app/kgtk/miniconda3/lib/python3.9/site-packages/kgtk/exceptions.py:90: UserWarning: Please raise KGTKException instead of <class 'ModuleNotFoundError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found

**Expected behavior**
Generate graph statistics of top relations from input file

**Screenshots**
N/A

**Desktop (please complete the following information):**
kgtk --version
KGTK 1.4.3

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by saggu** [comment]
Hi @versant2612 I think you are missing `graph-tool` in your kgtk environment. Install the required library by running the following command,

```
conda install -c conda-forge graph-tool
```

For future reference, run your command with `--debug` option to get the full error details.

```
kgtk --debug graph_statistics -i $GRAPH_STEP1 --log-file step1-claims.stat --output-statistics-only --compute-pagerank False --compute-hits False --output-degrees False
```

**Comment by versant2612** [comment]
@saggu thanks for suggestion. I had already installed it. I executed again. Here is the detailed log.

**conda install -c conda-forge graph-tool**
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /app/kgtk/miniconda3/envs/kgtk-env

  added / updated specs:
    - graph-tool

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.1.1s             |       h7f8727e_0         3.6 MB
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following packages will be UPDATED:

  openssl                                 1.1.1q-h7f8727e_0 --> 1.1.1s-h7f8727e_0 None

Proceed ([y]/n)? y

Downloading and Extracting Packages
openssl-1.1.1s       | 3.6 MB    | ########################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

(kgtk-env) root@vm096:/app# export GRAPH_STEP1=/app/kgtk/data/aux-tsv/step1-claims.tsv.gz

(kgtk-env) root@vm096:/app# kgtk **--debug** graph_statistics -i $GRAPH_STEP1 --log-file step1-claims.stat --output-statistics-only --compute-pagerank False --compute-hits False --output-degrees False

** (process:196593): WARNING **: 21:32:44.757: **Failed to load shared library 'libgdk-3.so.0**' referenced by the typelib: libXcursor.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/kgtk/exceptions.py", line 70, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/kgtk/cli/graph_statistics.py", line 174, in run
    import kgtk.gt.analysis_utils as gtanalysis
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/kgtk/gt/analysis_utils.py", line 2, in <module>
    import graph_tool.all as gtall
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/graph_tool/all.py", line 34, in <module>
    from graph_tool.draw import *
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/graph_tool/draw/__init__.py", line 848, in <module>
    from . cairo_draw import graph_draw, cairo_draw, \
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/graph_tool/draw/cairo_draw.py", line 1495, in <module>
    from gi.repository import Gtk, Gdk, GdkPixbuf
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/app/kgtk/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/app/kgtk/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/gi/overrides/Gdk.py", line 83, in <module>
    Color = override(Color)
  File "/app/kgtk/miniconda3/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
/app/kgtk/miniconda3/lib/python3.9/site-packages/kgtk/exceptions.py:90: UserWarning: Please raise KGTKException instead of <class 'AssertionError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found

I executed 

**sudo apt install libgtk-3-0**

And kgtk graph_statistics is runing now.

**Comment by saggu** [comment]
@versant2612 glad to help. Closing this issue
