### ISSUE TITLE
kgtk error from sh module upgrade

### ISSUE THREAD

**Issue by joelb-git** [usc-isi-i2/kgtk#696]
```
$ conda create -n kgtk-env-tmp python=3.9
$ conda activate kgtk-env-tmp
$ conda install -c conda-forge graph-tool
$ conda install -c conda-forge jupyterlab
$ pip --no-cache install -U kgtk

$ kgtk query -i /nas/material02/users/joelb/views/kgtk-notebooks/datasets/arnold/small-graph.tsv --match '()-[]->()'
Exception in thread background thread for pid 22626:
Traceback (most recent call last):
  File "/nas/material02/users/joelb/conda_envs/kgtk-env-tmp/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/nas/material02/users/joelb/conda_envs/kgtk-env-tmp/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/nas/material02/users/joelb/conda_envs/kgtk-env-tmp/lib/python3.9/site-packages/sh.py", line 1654, in wrap
    fn(*rgs, **kwargs)
  File "/nas/material02/users/joelb/conda_envs/kgtk-env-tmp/lib/python3.9/site-packages/sh.py", line 2656, in background_thread
    handle_exit_code(exit_code)
  File "/nas/material02/users/joelb/conda_envs/kgtk-env-tmp/lib/python3.9/site-packages/sh.py", line 2347, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/nas/material02/users/joelb/conda_envs/kgtk-env-tmp/lib/python3.9/site-packages/sh.py", line 838, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/tail '' -n +2

  STDOUT:


  STDERR:
/usr/bin/tail: cannot open ‘’ for reading: No such file or directory

local variable 'sqlproc' referenced before assignment
```

I traced the issue to an apparent regression in the `sh` module:

```
$ pip freeze | grep ^sh==
sh==2.0.2

$ pip uninstall sh
$ pip install sh==1.14.3
$ pip freeze | grep ^sh==
sh==1.14.3

$ kgtk query -i /nas/material02/users/joelb/views/kgtk-notebooks/datasets/arnold/small-graph.tsv --match '()-[]->()'
id      node1   label   node2
e1      m_shriver       spouse  a_schwarzenegger
e2      a_schwarzenegger        coactor l_hamilton
e3      g_rydstrom      colleague       g_borders
e4      g_rydstrom      colleague       a_schwarzenegger
e5      a_schwarzenegger        name    'Arnold Schwarzenegger'@de
e6      l_hamilton      name    'Linda Hamilton'@en
e7      g_rydstrom      name    'Gary R. Rydstrom'@en
e8      g_borders       name    'Gloria S. Borders'@en
e9      m_shriver       name    'Maria Shriver'@en
```

`sh` was updated to version 2.0.x on Feb 9, 2023: 
https://pypi.org/project/sh/#history

The current kgtk requirements show sh>=1.13, so the newer version gets
pulled:

https://github.com/usc-isi-i2/kgtk/blob/master/requirements.txt#L1

**Comment by saggu** [comment]
@joelb-git I created a new release, freezing the sh version: https://pypi.org/manage/project/kgtk/release/1.5.3/
